### ISSUE TITLE
Interactive webpage > Count, proportion and presence/ absence response variables > Generalised linear models

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical4#2]
Interactive webpage > Count, proportion and presence/ absence response variables > Generalised linear models > new paragraph

- I think we need to explain why we need generalise first and we are moving away from linear models 
  e.g. "In the last two weeks, we have been looking at linear models. These linear models assume that our resposne variable is normally distributed and so is our residuals and we have homogeneity of variance. For these analyses to be undertaken our response variable also needs to be continuous data so it can takeany value could be either positve and negative and run from -infintiy to +infinity. But what happens when we have a situation where our response variable does not follow a normal distribution or our response variable cannot be less than zero or the response variable is categorical. We then need a statistical test that will allow us analyse our data appropriately. This is when we need to think about generalising our linear model to deal with different types of distributions and response variables that are not continuous. Within this interactive tutorial, we will be looking at two commonly encountered types of generalised linear model (GLM): Poisson regression using count data and binary logistic regression using categorical data. GLMs allow us to tackle a much wider set of problems than linear models."

Interactive webpage > Count, proportion and presence/ absence response variables > Generalised linear models > paragraph 1

- This should be paragraph 2 and I would add a new subheading called "Data Types" then just reaffirm the differences in types of data. I'm wondering whether it mhtbe wise to go down the qualitative (categorical) and quantitative (numeric) route. We could do just a branching type diagram which shows these types of data which then maps over the list of examples you have in this section. I think the ratio in brackets is a bit confusing for them because it's not explained what ratio in this context is. We haven't mentioned the difference between ratio and interval scales.
  e.g. "Types of data
  
  You will be beginning to realise now that there are lots of different "types" of data. This is because we can collect information in so many different ways, manipulate those numbers and even create new types of data based on the observations that we make."

Interactive webpage > Count, proportion and presence/ absence response variables > Generalised linear models > Baseline assumptions section

- I think if we give a bit more clarity on the different types of data this will set up why we are teaching GLMs better. Then this section can be moved to its own page as a refresher before going onto look at Poisson and Binomial distributions.

Interactive webpage > Count, proportion and presence/ absence response variables > Generalised linear models > new paragraph above interactive

- I think the students needs some clear instruction about what to do here.
  e.g. "The interactive tool below will let you change the mean and the standard deviation so you can see how these two parameters alter the position along the x-axis and shape of the normal distribution alogn the x- and y-axes. The blue line represents a fitted curve over the histogram according to the Gaussian distribution which will help you visualise the bell-shape."

Interactive webpage > Count, proportion and presence/ absence response variables > Generalised linear models > comments
- This should be a sentence which gets them thinking about what they should have seen
e.g. ""You should have seen the following changes to the plot when you adjusted the mean and standard deviation:
1. as you increase or decrease the mean, the distribution moves to the left of the right, but remains roughly the same shape
2. a low standad deviation resutls in the values being packed together while a high standard deviation flattens and spreads the curve"

**Comment by rasanderson** [comment]
Most of these edits now done.
