### ISSUE TITLE
Interactive webpage > Count, proportion and presence/ absence response variables > Poisson and Binomial distributions

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical4#3]
Interactive webpage > Count, proportion and presence/ absence response variables > Poisson and Binomial distributions > paragraph 1

- The distributions need explained and linked to the type of data/ situation which you would use them. The why is missing at the start to draw them in.
  e.g. "When we move from a linear model to using a GLM, we will need to think about changing the distribution we use or are assuming from our data. If we undertake a GLM using a Gaussian distribution this is very similar to just doing a linear model which we have already gone through and doesn't deal with the issues. The reason we are switching to a GLM is because our data need us to think in a generalised framework, which requires a different distribution. The two distributions you are most likely to need as biologists are the Poisson distribution for counts named after Simeon Poisson (French mathematician), and the Binomial distribution for 1/0 or presence/absence data (no-one seems to have claimed credit for this one!).
  
  Let’s have a quick look at these two distributions and hopefully this will become clearer."

Interactive webpage > Count, proportion and presence/ absence response variables > Poisson and Binomial distributions > paragraph 2

- You've not introduced the Poisson distribution yet so not sure what/ where they would be remembering it from!
  e.g. ""Often biologists and ecologist collect data in the form of counts e.g. the number of individuals in quadrat or number of fish in a trawl. These numbers are whole numbers or integers and cannot be negative values or have decimal points. This means that our distribution cannot include numbers less than zero. The Poisson distribution allows us to model count data. It takes a parameter λ (Greek letter lambda) which adjusts the shape of this distribution. Try mvoing the the interactive slider left and right to see what happens to the size adn shape of the distribution:"

Interactive webpage > Count, proportion and presence/ absence response variables > Poisson and Binomial distributions > paragraph 3

- Change "Note" to a sentence
  e.g. "You should have seen the following things happen to the distribution when you moved the slider:"

Interactive webpage > Count, proportion and presence/ absence response variables > Poisson and Binomial distributions > paragraph 5

- Just need to make the sentnce a bit clearer
  e.g. "There are times when you will collect data that has a binary response. This could be:"

Interactive webpage > Count, proportion and presence/ absence response variables > Poisson and Binomial distributions > paragraph 7

- spelling error - "How to we then calculate" should be "How do we calculate:"

Interactive webpage > Count, proportion and presence/ absence response variables > Poisson and Binomial distributions > Note section

- Move first bullet point to pargraph 7 because they will probably start playing with the slidders before they read the "Note" section.
"In the interactive demonstration below, we have the simplest setup, 25 replicates, with each of size one (which produces a very simple plot). Before you adjust the sliders, the sample size is only 1 (e.g. one seed per) replicate, and the probability (of germination) is 0.5. Therefore roughly half of your 25 replicates will fall into the 0 (no germination) category, and half into the 1.0 (germination) category. Adjust the size of each replicate, which is equivalent to the number of seeds per replicate in the example above, and the probability of success, equivalent to the probability of germination."

**Comment by rasanderson** [comment]
Resolved as suggested
