### ISSUE TITLE
Interactive webpage > Count, proportion and presence/ absence response variables > How to generalise

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical4#4]
Interactive webpage > Count, proportion and presence/ absence response variables > How to generalise > paragraph 7

- Spelling - "How to we then calculate" should be "How do we then calculate"

Interactive webpage > Count, proportion and presence/ absence response variables > How to generalise > paragraph 8

- I would alter the bullet points so that link function comes first, which distribution is relates to and what data is being used. This might make more conceptual sense for the students.
"There are 3 link functions which we need to know about, for now, which relate to the 3 distributions we have been through:

identity = when we need to use a normal (Gaussian) distribution. This is used with the linear models we have already discussed in weeks 2 and 3.
log link = when we need to use a Poisson distribution and we have count data. This uses natural logs rather than logs to base 10 to model the response variable.
logit link = when we need to use a binomial distribution and our response variable is binary. This is a little more complex, but R sets it automatically.

Fortunately, R’s glm() function automatically picks the correct transformation for the link function."

**Comment by rasanderson** [comment]
Resolved as requested
