### ISSUE TITLE
Interactive webpage > Count, proportion and presence/ absence response variables > GLM with count data

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical4#5]
Interactive webpage > Count, proportion and presence/ absence response variables > GLM with count data > pargraph 8

- I think it would be good to get them putting the link funciton into the glm(). This will hopefully mean that they pick up which function to use rather it being a black box.

"Now let's analyse these using GLM instead using the correct distribution and link function. R will automatically pick the correct transformation for the link function but we will state it so it will help you connect the statistical distribution to the appropriate link function and you will see where you would need to state it when writing the R code. We need to alter slightly what we put into the model:

`glm(response ~ explanatory, family = distribution(link ="X"), data =  data_set)`

You can see an extra term in the model which is `family = ` that relates to the distribution we will be using and specifies the link function. Since we are using count data, the correct distribution we will need to use is the Poisson distribution and the link function will be log. Thinking about the linear model which you just created, simply replace your original lm() function with glm() and add `family = poisson(link = "log")`. Again display the model summary() and diagnostic plots."

Interactive webpage > Count, proportion and presence/ absence response variables > GLM with count data > code box 3

- I think we add the link term because we need to hammer home that connection between the distribution and link function.
`sppcount_glm <- glm(species~pollution, family = poisson(link = "log"), data=sppcount)`

Interactive webpage > Count, proportion and presence/ absence response variables > GLM with count data > question box

- Maximum likelihood hasn't been introduced. Should this be introduced in the How to Generalise page. Highlight that lm() uses least squares and glm() use maximum likelihood or is this concept too much at stage 2. Andy Beckermann's Getting started with r gives a nice very light touch to likelihood (https://academic.oup.com/book/27290/chapter/196938074)

Interactive webpage > Count, proportion and presence/ absence response variables > GLM with count data > new final paragraph

- I think we need something that shows the students how to write their results up based on the information in the summary table like was done for the regression and ANOVA sections. This will need to be done for the GLM for binary data as well. I get confused at times about how to present/ report the coefficients.

**Comment by rasanderson** [comment]
Resolved as suggested
