### ISSUE TITLE
Interactive webpage > Count, proportion and presence/ absence response variables > Summary/ additional reading page

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical4#6]
Andy Beckermann has got a really good chapter on GLMs with count data. I think we point the students here for additional reading:

7 Getting Started with Generalized Linear Models: https://academic.oup.com/book/27290/chapter/196938074

I've still not found a good reference which is stage two level for GLM with binary data. Chapter 13 (Generalised linear models and logistic regression) in Quinn and Keough is quite dense but Zuur's Analysis Ecological Data chapter 6 is a bit better.

**Comment by rasanderson** [comment]
Resolved as suggested - I also can't think of a good binomial intro but will keep looking!
